---
- name: Docker playbook
  hosts: all
  become: true
  tasks:

    - name: Update repository cache
      apt:
        update_cache: true

    - name: Install latest docker
      apt:
        name: docker
        state: latest

    - name: Install latest docker compose
      apt:
        name: docker-compose
        state: latest

