---
- name: Remove docker from system
  hosts: all
  become: true
  tasks:

    - name: Remove docker
      apt:
        name: docker
        state: absent

    - name: Remove docker compose
      apt:
        name: docker-compose
        state: absent

